-- Align the physical database schema with the domain design specification.
-- This migration is written to work on both:
-- 1) an existing database that was partially generated by Hibernate ddl-auto, and
-- 2) a fresh database where only V1-V5 have run before this migration.

-- ---------------------------------------------------------------------------
-- Create domain tables that were previously produced implicitly by Hibernate.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accommodations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    category VARCHAR(30) NOT NULL,
    location VARCHAR(500) NOT NULL,
    business_license VARCHAR(100) NOT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    thumbnail_url VARCHAR(500) NULL,
    submit_date DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    accommodation_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    capacity INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_cars (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    license_plate VARCHAR(20) NOT NULL UNIQUE,
    car_type VARCHAR(30) NOT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    target_type VARCHAR(10) NOT NULL,
    target_id BIGINT NOT NULL,
    check_in DATETIME NOT NULL,
    check_out DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RESERVED',
    total_price DECIMAL(12,2) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    target_type VARCHAR(10) NOT NULL,
    target_id BIGINT NOT NULL,
    date DATE NOT NULL,
    base_price DECIMAL(12,2) NOT NULL,
    stock INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reservation_id BIGINT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    pg_amount DECIMAL(12,2) NOT NULL,
    used_mileage INT NOT NULL DEFAULT 0,
    accumulated_mileage INT NOT NULL DEFAULT 0,
    imp_uid VARCHAR(100) UNIQUE NULL,
    merchant_uid VARCHAR(100) NOT NULL UNIQUE,
    reservation_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mileage_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount INT NOT NULL,
    log_type VARCHAR(10) NOT NULL,
    description TEXT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    settlement_date DATE NOT NULL,
    gross_amount DECIMAL(14,2) NOT NULL,
    commission DECIMAL(14,2) NOT NULL,
    net_amount DECIMAL(14,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    requested_at DATETIME NULL,
    approved_at DATETIME NULL,
    finalized_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS properties (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    address_name VARCHAR(500) NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    registered_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    like_count INT NOT NULL DEFAULT 0,
    comment_count INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_images (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    sort_order INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fcm_tokens (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id BIGINT NOT NULL,
    fcm_token VARCHAR(300) NOT NULL,
    device_type VARCHAR(20) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS guide_markers (
    marker_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(30) NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_likes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    UNIQUE KEY uk_post_likes_post_member (post_id, member_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Rename legacy Hibernate-generated PK columns to the domain spec's id names.
-- ---------------------------------------------------------------------------
ALTER TABLE rooms DROP FOREIGN KEY IF EXISTS FKhs0375t8hfjka9aswlo4yv6nv;
ALTER TABLE rooms DROP FOREIGN KEY IF EXISTS fk_rooms_accommodation;

ALTER TABLE accommodations CHANGE COLUMN IF EXISTS accommodation_id id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE rooms CHANGE COLUMN IF EXISTS room_id id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE rental_cars CHANGE COLUMN IF EXISTS car_id id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE reservations CHANGE COLUMN IF EXISTS reservation_id id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE inventory CHANGE COLUMN IF EXISTS inventory_id id BIGINT NOT NULL AUTO_INCREMENT;

-- ---------------------------------------------------------------------------
-- Remove columns not present in the domain design.
-- ---------------------------------------------------------------------------
ALTER TABLE flight_routes DROP COLUMN IF EXISTS route_code;
ALTER TABLE flight_routes DROP COLUMN IF EXISTS distance_km;

-- ---------------------------------------------------------------------------
-- Normalize column types/defaults to the domain spec.
-- ---------------------------------------------------------------------------
ALTER TABLE members MODIFY email VARCHAR(100) NULL;
ALTER TABLE members MODIFY name VARCHAR(100) NULL;
ALTER TABLE members MODIFY role VARCHAR(20) NOT NULL;
ALTER TABLE members MODIFY provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE members MODIFY status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
CREATE UNIQUE INDEX IF NOT EXISTS uk_members_email ON members(email);

ALTER TABLE flight_routes MODIFY seller_id BIGINT NOT NULL;
ALTER TABLE flight_routes MODIFY duration_minutes INT NOT NULL;
ALTER TABLE flight_routes MODIFY status VARCHAR(20) NOT NULL DEFAULT 'PENDING_APPROVAL';

ALTER TABLE flight_schedules MODIFY route_id BIGINT NOT NULL;
ALTER TABLE flight_schedules MODIFY status VARCHAR(20) NOT NULL DEFAULT 'PENDING_APPROVAL';

ALTER TABLE seat_inventories MODIFY flight_schedule_id BIGINT NOT NULL;
ALTER TABLE seat_inventories MODIFY class_type VARCHAR(15) NOT NULL;

ALTER TABLE flight_bookings MODIFY flight_schedule_id BIGINT NOT NULL;
ALTER TABLE flight_bookings MODIFY seat_class VARCHAR(15) NOT NULL;
ALTER TABLE flight_bookings MODIFY status VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT';

ALTER TABLE insurance_products MODIFY coverage_details JSON NOT NULL;
ALTER TABLE insurance_products MODIFY status VARCHAR(20) NOT NULL DEFAULT 'PENDING_APPROVAL';
ALTER TABLE insurance_policies MODIFY insurance_product_id BIGINT NOT NULL;
ALTER TABLE insurance_policies MODIFY status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE accommodations MODIFY approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE rental_cars MODIFY approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE reservations MODIFY target_type VARCHAR(10) NOT NULL;
ALTER TABLE reservations MODIFY status VARCHAR(20) NOT NULL DEFAULT 'RESERVED';
ALTER TABLE inventory MODIFY target_type VARCHAR(10) NOT NULL;

ALTER TABLE payments MODIFY status VARCHAR(20) NOT NULL;
ALTER TABLE mileage_logs MODIFY log_type VARCHAR(10) NOT NULL;
ALTER TABLE seller_accounts MODIFY status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE settlements MODIFY status VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE posts MODIFY type VARCHAR(20) NOT NULL;
ALTER TABLE posts MODIFY status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE fcm_tokens MODIFY device_type VARCHAR(20) NULL;
ALTER TABLE guide_markers MODIFY category VARCHAR(30) NOT NULL;

-- Remove microsecond precision from Hibernate-generated DATETIME(6) columns.
ALTER TABLE accommodations MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE accommodations MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE rooms MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE rooms MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE rental_cars MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE rental_cars MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE reservations MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reservations MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE inventory MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE inventory MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE payments MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE payments MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE posts MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE fcm_tokens MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE fcm_tokens MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE settlements MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE settlements MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------
-- Recreate/ensure physical FK constraints explicitly required by the domain ERD.
-- ---------------------------------------------------------------------------
ALTER TABLE comments DROP FOREIGN KEY IF EXISTS FKh4c7lvsc298whoyd4w9ta25cr;
ALTER TABLE comments DROP FOREIGN KEY IF EXISTS FKkv22t54g17a6hvj7hbn6byh5s;
ALTER TABLE comments DROP FOREIGN KEY IF EXISTS fk_comments_post;
ALTER TABLE comments DROP FOREIGN KEY IF EXISTS fk_comments_member;
ALTER TABLE post_images DROP FOREIGN KEY IF EXISTS fk_post_images_post;
ALTER TABLE fcm_tokens DROP FOREIGN KEY IF EXISTS fk_fcm_tokens_member;
ALTER TABLE post_likes DROP FOREIGN KEY IF EXISTS fk_post_likes_post;
ALTER TABLE post_likes DROP FOREIGN KEY IF EXISTS fk_post_likes_member;
ALTER TABLE posts DROP FOREIGN KEY IF EXISTS fk_posts_member;

ALTER TABLE rooms
    ADD CONSTRAINT fk_rooms_accommodation
        FOREIGN KEY (accommodation_id) REFERENCES accommodations(id);
ALTER TABLE posts
    ADD CONSTRAINT fk_posts_member
        FOREIGN KEY (member_id) REFERENCES members(id);
ALTER TABLE post_images
    ADD CONSTRAINT fk_post_images_post
        FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE fcm_tokens
    ADD CONSTRAINT fk_fcm_tokens_member
        FOREIGN KEY (member_id) REFERENCES members(id);
ALTER TABLE comments
    ADD CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE comments
    ADD CONSTRAINT fk_comments_member
        FOREIGN KEY (member_id) REFERENCES members(id);
ALTER TABLE post_likes
    ADD CONSTRAINT fk_post_likes_post
        FOREIGN KEY (post_id) REFERENCES posts(id);
ALTER TABLE post_likes
    ADD CONSTRAINT fk_post_likes_member
        FOREIGN KEY (member_id) REFERENCES members(id);
