# Trigger deploy
spring:
  profiles:
    include: api 
  main:
    allow-bean-definition-overriding: true 
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
  server-header: ""

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000    # 30분
  refresh-token-expiration: 1209600000 # 14일

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    cloudfront-domain: ${AWS_CLOUDFRONT_DOMAIN}
    region: ${AWS_REGION}
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /api/v1
      discovery:
        enabled: false
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
  health:
    defaults:
      enabled: false    